FROM node:8.5.0

WORKDIR /app

VOLUME /logs

COPY package.json /app/
RUN npm install

COPY backend dbs run-api.sh /app/
RUN chmod +x run-api.sh

EXPOSE 8080

ENV NODE_ENV=production
ENV LISTENPORT=8080

ENTRYPOINT ["./run-api.sh"]