FROM node:8.5.0

ENV NODE_ENV=production \
    LISTENPORT=8080 \
    FRONT_END_DOMAIN="wsdl-docker.cs.odu.edu" \
    FRONT_END_LOC="http://wsdl-docker.cs.odu.edu:8080" \
    OUT_SIDE_DOCKER_PORT=8880 \
    API_ENDPOINT="http://wsdl-docker.cs.odu.edu:8880"

WORKDIR /app

VOLUME /logs

COPY package.json /app/
RUN npm install

COPY backend/ public/ pug/ run-backend.sh /app/

RUN chmod +x run-backend.sh


EXPOSE 8080

ENTRYPOINT ["./run-backend.sh"]
