FROM node:8.5.0

WORKDIR /app

VOLUME /logs

COPY package.json /app/
RUN npm install

COPY backend public pug run-backend.sh /app/

RUN chmod +x run-backend.sh

ENV NODE_ENV=production
ENV LISTENPORT=8080
ENV FRONT_END_DOMAIN="wsdl-docker.cs.odu.edu"
ENV FRONT_END_LOC="http://wsdl-docker.cs.odu.edu:8080"
ENV OUT_SIDE_DOCKER_PORT=8880
ENV API_ENDPOINT="http://wsdl-docker.cs.odu.edu:8880"

EXPOSE 8080

ENTRYPOINT ["./run-backend.sh"]
